### ISSUE TITLE
Persist fails to write all data

### ISSUE THREAD

**Issue by trevormunoz** [umd-mith/mith-static#10]
```
> mith-static@0.1.0 persist
> node scripts/persist.js

wrote /Users/umd-laptop/Code/mith-static/static/data/groups.json
wrote /Users/umd-laptop/Code/mith-static/static/data/posts.json
wrote /Users/umd-laptop/Code/mith-static/static/data/people.json
wrote /Users/umd-laptop/Code/mith-static/static/data/identities.json
wrote /Users/umd-laptop/Code/mith-static/static/data/research.json
(node:96515) UnhandledPromiseRejectionWarning: Error: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'research' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    |     property 'events' -> object with constructor 'Array'
    --- index 0 closes the circle
    at Persistor.persistEvents (/Users/umd-laptop/Code/mith-static/scripts/persist.js:524:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:96515) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:96515) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by edsu** [comment]
I think this is more of an error than a warning since it seems to prevent events.json from being written?
